# GET root route
GET http://localhost:5273

###
# GET all games
GET http://localhost:5273/games

###
# GET game by id
GET http://localhost:5273/games/7c7792bd-aceb-492a-8cbd-f4c3efc4d486

###
# POST a new game
POST http://localhost:5273/games
Content-Type: application/json

{
  "name": "FIFA 2025",
  "genreId": "73edf7d0-8201-455a-bb47-7aa16f9bd2eb",
  "price": 59.99,
  "releaseDate": "2025-09-27",
  "description": "The latest installment in the FIFA series."
}

###
// PUT game by id
PUT http://localhost:5273/games/7c7792bd-aceb-492a-8cbd-f4c3efc4d486
Content-Type: application/json

{
  "name": "FIFA 2025",
  "genreId": "73edf7d0-8201-455a-bb47-7aa16f9bd2eb",
  "price": 69.99,
  "releaseDate": "2025-09-27",
  "description": "The latest installment in the FIFA series."
}

###
// DELETE game by id
DELETE http://localhost:5273/games/7c7792bd-aceb-492a-8cbd-f4c3efc4d486

###
// GET all genres
GET http://localhost:5273/genres
